/*
 * This source file was generated by the Gradle 'init' task
 */
package org.banking.management;

import org.banking.management.dao.AccountantDao;
import org.banking.management.dao.AccountantDaoImplementation;
import org.banking.management.dao.CustomerDaoImplementation;
import org.banking.management.entity.Accountant;
import org.banking.management.exception.CustomerException;
import org.banking.management.utils.PasswordUtils;

import java.util.Scanner;

public class App {

  public static void main(String[] args) {
    Scanner sc = new Scanner(System.in);

    for (;;) {
      System.out.println("------------WELCOME TO ONLINE BANKING SYSTEM------------");
      System.out.println("--------------------------------------------------------");
      System.out.println("1. ADMIN LOGIN PORTAL \r\n" + "2. CUSTOMER");

      System.out.println("Choose your option");
      int choice = sc.nextInt();

      switch (choice) {
        case 1:
          System.out.println("ADMIN LOGIN CREDENTIALS ---------------- ACCOUNTANT");
          System.out.println("ENTER USERNAME: ");
          String username = sc.next();
          System.out.println("ENTER PASSWORD: ");
          String password = sc.next();

          AccountantDao accountantDao = new AccountantDaoImplementation();

          try {
            Accountant accountant = accountantDao.loginAccountant(username, password);
            if (accountant == null) {
              System.out.println("WRONG CREDENTIALS");
              break;
            }

            System.out.println("LOGIN SUCCESSFUL!!!!");

            System.out
                .println("WELCOME " + accountant.getUserName().toUpperCase() + " AS ADMIN OF ONLINE BANKING SYSTEM");

            for (;;) {
              System.out.println("---------------------------\r\n" +
                  "1. Add New Customer Account \r\n");
              int accountantChoice = sc.nextInt();
              if (accountantChoice == 1) {
                System.out.println("--------New Account For Customer---------");
                System.out.println("Enter Customer Name :");
                String customerName = sc.next();
                System.out.println("Enter Customer Email :");
                String customerEmail = sc.next();
                System.out.println("Enter Customer Password :");
                String customerPassword = sc.next();
                System.out.println("Enter Customer Contact No :");
                String customerContact = sc.next();
                System.out.println("Enter Customer Address :");
                String customerAddress = sc.next();
                System.out.println("Enter the initial amount the customer wants to deposit");
                int initialDeposit = sc.nextInt();
                int customerId = -1;
                try {
                  customerId = new CustomerDaoImplementation().addCustomer(customerName, customerEmail,
                      PasswordUtils.hashPassword(customerPassword), customerContact, customerAddress, initialDeposit);
                } catch (CustomerException e) {
                  System.out.println(e.getMessage());
                }
                System.out.println("-----------------------------------");
              }
            }
          } catch (Exception e) {
            System.out.println(e.getMessage());
          }
      }
      sc.close();
    }
  }
}
