/*
 * This source file was generated by the Gradle 'init' task
 */
package org.banking.management;

import org.banking.management.dao.AccountantDao;
import org.banking.management.dao.AccountantDaoImplementation;
import org.banking.management.dao.CustomerDaoImplementation;
import org.banking.management.entity.Accountant;
import org.banking.management.exception.AccountantException;
import org.banking.management.exception.CustomerException;
import org.banking.management.utils.PasswordUtils;

import java.util.Scanner;

public class App {

  public static void main(String[] args) {
    Scanner sc = new Scanner(System.in);
    for (;;) {
          System.out.println("------------WELCOME TO ONLINE BANKING SYSTEM------------");
          System.out.println("--------------------------------------------------------");
          System.out.println("1. ADMIN LOGIN PORTAL \n2. CUSTOMER");
          System.out.println("Choose your option: ");

          int choice = sc.nextInt();

          switch (choice) {
              case 1 -> {
                  System.out.println("ADMIN LOGIN CREDENTIALS ---------------- ACCOUNTANT");
                  System.out.print("ENTER USERNAME: ");
                  String username = sc.next();
                  System.out.print("ENTER PASSWORD: ");
                  String password = sc.next();

                  AccountantDao accountantDao = new AccountantDaoImplementation();

                  try {
                      Accountant accountant = accountantDao.loginAccountant(username, password);

                      if (accountant == null) {
                          System.out.println("❌ WRONG CREDENTIALS");
                          continue;
                      }

                      System.out.println("✅ LOGIN SUCCESSFUL!!!!");
                      System.out.println("WELCOME " + accountant.getUserName().toUpperCase() + " AS ADMIN");

                      // Admin menu loop
                      for (;;) {
                          System.out.println("---------------------------");
                          System.out.println("1. Add New Customer Account");
                          System.out.println("0. Logout");
                          int accountantChoice = sc.nextInt();

                          if (accountantChoice == 1) {
                              try {
                                  System.out.println("-------- New Account For Customer ---------");
                                  System.out.print("Enter Customer Name: ");
                                  String customerName = sc.next();
                                  System.out.print("Enter Customer Email: ");
                                  String customerEmail = sc.next();
                                  System.out.print("Enter Customer Password: ");
                                  String customerPassword = sc.next();
                                  System.out.print("Enter Customer Contact No: ");
                                  String customerContact = sc.next();
                                  System.out.print("Enter Customer Address: ");
                                  String customerAddress = sc.next();
                                  System.out.print("Enter the initial deposit: ");
                                  int initialDeposit = sc.nextInt();

                                  int customerId = new CustomerDaoImplementation().addCustomer(
                                          customerName,
                                          customerEmail,
                                          PasswordUtils.hashPassword(customerPassword),
                                          customerContact,
                                          customerAddress,
                                          initialDeposit
                                  );

                                  System.out.println("✅ Customer added successfully with ID: " + customerId);
                              } catch (CustomerException e) {
                                  System.out.println("❌ " + e.getMessage());
                              }
                          } else if (accountantChoice == 0) {
                              System.out.println("Logging out...");
                              break; // exit admin menu
                          }
                      }

                  } catch (AccountantException e) {
                      System.out.println("❌ Error: " + e.getMessage());
                  } catch (Exception e) {
                      System.out.println("⚠️ Unexpected error: " + e.getMessage());
                  }
              }

              case 2 -> {
                  System.out.println("Customer portal not implemented yet...");
              }

              default -> {
                  System.out.println("❌ Invalid option, try again.");
              }
          }
      }
  }
}
